FROM python:3.14.6-trixie

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends locales && locale-gen C.UTF-8 && apt-get install -y python3-full python3-pip htop curl jq git vim nmap iputils-ping nvtop && rm -rf /var/lib/apt/lists/*

ENV LANG=C.UTF-8
ENV LANGUAGE=C.UTF-8
ENV LC_ALL=C.UTF-8

ENV PYTHONUTF8=1
ENV PYTHONIOENCODING=UTF-8
ENV PYTHONUNBUFFERED=1

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade torch --break


ARG version=prod

LABEL authors="RadLab"
LABEL version=$version

COPY . /srv/llm-router-services

WORKDIR /srv/llm-router-services

RUN pip3 install --upgrade --no-cache-dir . --break
#RUN pip3 install --upgrade --no-cache-dir -r requirements.txt --break

RUN cp docker/entrypoint.sh entrypoint.sh && chmod +x entrypoint.sh

ARG USER_ID=5000
ARG GROUP_ID=5000
RUN groupadd -g ${GROUP_ID} llm-router && \
    useradd -m -u ${USER_ID} -g llm-router -d /home/llm-router llm-router && \
    chown -R llm-router:llm-router /srv

USER llm-router

RUN mkdir -p /srv/cache && chown llm-router:llm-router /srv/cache
ENV HF_HOME=/srv/cache

ENTRYPOINT ["/srv/llm-router-services/entrypoint.sh"]
